// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8W2v6vyUgdS5UgRP-ZghV2Sfa-rIr6nk',
    appId: '1:562869960811:web:513578c3224cf4e6cb312e',
    messagingSenderId: '562869960811',
    projectId: 'flutrsimpleemployeescrud',
    authDomain: 'flutrsimpleemployeescrud.firebaseapp.com',
    storageBucket: 'flutrsimpleemployeescrud.appspot.com',
    measurementId: 'G-DEJ796DYSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8chBfbb6t4EqHtz9veK4Tdx-KDe2sEvQ',
    appId: '1:562869960811:android:73f56920b22fcaeccb312e',
    messagingSenderId: '562869960811',
    projectId: 'flutrsimpleemployeescrud',
    storageBucket: 'flutrsimpleemployeescrud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTtUKb0uYiGWtohJ2RQx7q-1arpllWE-o',
    appId: '1:562869960811:ios:89353c382d3c0a5dcb312e',
    messagingSenderId: '562869960811',
    projectId: 'flutrsimpleemployeescrud',
    storageBucket: 'flutrsimpleemployeescrud.appspot.com',
    iosBundleId: 'com.example.flutrSimpleEmployeesCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTtUKb0uYiGWtohJ2RQx7q-1arpllWE-o',
    appId: '1:562869960811:ios:061466c2548b3817cb312e',
    messagingSenderId: '562869960811',
    projectId: 'flutrsimpleemployeescrud',
    storageBucket: 'flutrsimpleemployeescrud.appspot.com',
    iosBundleId: 'com.example.flutrSimpleEmployeesCrud.RunnerTests',
  );
}
